# Generated by Django 4.2.7 on 2024-01-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='ФИО')),
                ('numb', models.IntegerField(max_length=15, verbose_name='Номер телефона')),
                ('mail', models.CharField(max_length=50, verbose_name='Почта')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('empl', models.CharField(max_length=30, verbose_name='ФИО сотрудника')),
                ('memory', models.IntegerField(max_length=4, verbose_name='Память')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ФИО')),
                ('numb', models.IntegerField(verbose_name='Номер телефона')),
                ('post', models.CharField(max_length=30, verbose_name='Должность')),
                ('salary', models.IntegerField(verbose_name='З\\П')),
                ('bonus', models.IntegerField(max_length=3, verbose_name='Процент премии')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('memory', models.IntegerField(max_length=4, verbose_name='Память')),
                ('count', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
    ]
