# Generated by Django 4.2.7 on 2024-01-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='memory',
            field=models.IntegerField(verbose_name='Память'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='numb',
            field=models.IntegerField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='bonus',
            field=models.IntegerField(verbose_name='Процент премии'),
        ),
        migrations.AlterField(
            model_name='models',
            name='memory',
            field=models.IntegerField(verbose_name='Память'),
        ),
    ]
