# Generated by Django 4.2.7 on 2024-01-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='fio',
            field=models.CharField(max_length=30, verbose_name='имя'),
        ),
    ]
